// <auto-generated />
using Arcade_mania_backend_webAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcade_mania_backend_webAPI.Migrations
{
    [DbContext(typeof(GameScoresDbContext))]
    [Migration("20251130125037_UserControllerReady")]
    partial class UserControllerReady
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Arcade_mania_backend_webAPI.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("FighterHighScore")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("fighter_high_score");

                    b.Property<uint>("MemoryHighScore")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("memory_high_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("SnakeHighScore")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("snake_high_score");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "uq_users_name")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
